# Generated by Django 4.1.4 on 2022-12-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_no", models.CharField(max_length=5)),
                ("name", models.CharField(max_length=100)),
                ("phone", models.DecimalField(decimal_places=0, max_digits=13)),
                ("salary", models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_no", models.CharField(max_length=5)),
                ("name", models.CharField(max_length=100)),
                ("grade", models.CharField(max_length=2)),
                ("gender", models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_no", models.CharField(max_length=5)),
                ("name", models.CharField(max_length=100)),
                ("phone", models.DecimalField(decimal_places=0, max_digits=13)),
                ("salary", models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
    ]
