# Generated by Django 4.1.4 on 2022-12-30 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("all_models", "0002_alter_employee_phone_alter_employee_salary_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="employee", name="id_no",),
        migrations.RemoveField(model_name="student", name="id_no",),
        migrations.RemoveField(model_name="teacher", name="id_no",),
    ]
